const SET_CATEGORIES = 'SET_CATEGORY_CREATE_CV';
const SET_PROFESSIONS = 'SET_PROFESSIONS_CREATE_CV'
const SET_VALUE = 'SET_REDUCER_VALUE_CREATE_CV';
const ADD_VIDEO = 'ADD_VIDEO_CREATE_CV';
const POSTED_CV = 'POSTED_CV'
const SET_LOADING = 'SET_USER_LOADING';

export { SET_CATEGORIES, SET_VALUE, ADD_VIDEO, SET_PROFESSIONS, POSTED_CV, SET_LOADING };
